//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_LuaWindowWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FairyGUI.LuaWindow), typeof(FairyGUI.Window));
		L.RegFunction("ConnectLua", ConnectLua);
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("New", _CreateFairyGUI_LuaWindow);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFairyGUI_LuaWindow(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				FairyGUI.LuaWindow obj = new FairyGUI.LuaWindow();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: FairyGUI.LuaWindow.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ConnectLua(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			FairyGUI.LuaWindow obj = (FairyGUI.LuaWindow)ToLua.CheckObject<FairyGUI.LuaWindow>(L, 1);
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			obj.ConnectLua(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FairyGUI.LuaWindow obj = (FairyGUI.LuaWindow)ToLua.CheckObject<FairyGUI.LuaWindow>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

