//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class System_Collections_Generic_Stack_FairyGUI_GComponentWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(System.Collections.Generic.Stack<FairyGUI.GComponent>), typeof(System.Object), "Stack_FairyGUI_GComponent");
		L.RegFunction("Clear", Clear);
		L.RegFunction("Contains", Contains);
		L.RegFunction("CopyTo", CopyTo);
		L.RegFunction("Peek", Peek);
		L.RegFunction("Pop", Pop);
		L.RegFunction("Push", Push);
		L.RegFunction("ToArray", ToArray);
		L.RegFunction("TrimExcess", TrimExcess);
		L.RegFunction("GetEnumerator", GetEnumerator);
		L.RegFunction("New", _CreateSystem_Collections_Generic_Stack_FairyGUI_GComponent);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Count", get_Count, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSystem_Collections_Generic_Stack_FairyGUI_GComponent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				System.Collections.Generic.Stack<FairyGUI.GComponent> obj = new System.Collections.Generic.Stack<FairyGUI.GComponent>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<System.Collections.Generic.IEnumerable<FairyGUI.GComponent>>(L, 1))
			{
				System.Collections.Generic.IEnumerable<FairyGUI.GComponent> arg0 = (System.Collections.Generic.IEnumerable<FairyGUI.GComponent>)ToLua.ToObject(L, 1);
				System.Collections.Generic.Stack<FairyGUI.GComponent> obj = new System.Collections.Generic.Stack<FairyGUI.GComponent>(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<int>(L, 1))
			{
				int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
				System.Collections.Generic.Stack<FairyGUI.GComponent> obj = new System.Collections.Generic.Stack<FairyGUI.GComponent>(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: System.Collections.Generic.Stack<FairyGUI.GComponent>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.Stack<FairyGUI.GComponent> obj = (System.Collections.Generic.Stack<FairyGUI.GComponent>)ToLua.CheckObject<System.Collections.Generic.Stack<FairyGUI.GComponent>>(L, 1);
			obj.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Contains(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.Stack<FairyGUI.GComponent> obj = (System.Collections.Generic.Stack<FairyGUI.GComponent>)ToLua.CheckObject<System.Collections.Generic.Stack<FairyGUI.GComponent>>(L, 1);
			FairyGUI.GComponent arg0 = (FairyGUI.GComponent)ToLua.CheckObject<FairyGUI.GComponent>(L, 2);
			bool o = obj.Contains(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CopyTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			System.Collections.Generic.Stack<FairyGUI.GComponent> obj = (System.Collections.Generic.Stack<FairyGUI.GComponent>)ToLua.CheckObject<System.Collections.Generic.Stack<FairyGUI.GComponent>>(L, 1);
			FairyGUI.GComponent[] arg0 = ToLua.CheckObjectArray<FairyGUI.GComponent>(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.CopyTo(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Peek(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.Stack<FairyGUI.GComponent> obj = (System.Collections.Generic.Stack<FairyGUI.GComponent>)ToLua.CheckObject<System.Collections.Generic.Stack<FairyGUI.GComponent>>(L, 1);
			FairyGUI.GComponent o = obj.Peek();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Pop(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.Stack<FairyGUI.GComponent> obj = (System.Collections.Generic.Stack<FairyGUI.GComponent>)ToLua.CheckObject<System.Collections.Generic.Stack<FairyGUI.GComponent>>(L, 1);
			FairyGUI.GComponent o = obj.Pop();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Push(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			System.Collections.Generic.Stack<FairyGUI.GComponent> obj = (System.Collections.Generic.Stack<FairyGUI.GComponent>)ToLua.CheckObject<System.Collections.Generic.Stack<FairyGUI.GComponent>>(L, 1);
			FairyGUI.GComponent arg0 = (FairyGUI.GComponent)ToLua.CheckObject<FairyGUI.GComponent>(L, 2);
			obj.Push(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToArray(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.Stack<FairyGUI.GComponent> obj = (System.Collections.Generic.Stack<FairyGUI.GComponent>)ToLua.CheckObject<System.Collections.Generic.Stack<FairyGUI.GComponent>>(L, 1);
			FairyGUI.GComponent[] o = obj.ToArray();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TrimExcess(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.Stack<FairyGUI.GComponent> obj = (System.Collections.Generic.Stack<FairyGUI.GComponent>)ToLua.CheckObject<System.Collections.Generic.Stack<FairyGUI.GComponent>>(L, 1);
			obj.TrimExcess();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetEnumerator(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.Stack<FairyGUI.GComponent> obj = (System.Collections.Generic.Stack<FairyGUI.GComponent>)ToLua.CheckObject<System.Collections.Generic.Stack<FairyGUI.GComponent>>(L, 1);
			System.Collections.IEnumerator o = obj.GetEnumerator();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Count(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			System.Collections.Generic.Stack<FairyGUI.GComponent> obj = (System.Collections.Generic.Stack<FairyGUI.GComponent>)o;
			int ret = obj.Count;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Count on a nil value");
		}
	}
}

